# SPDX-License-Identifier: GPL-2.0-only

obj-y += kernel/ drivers/ subarch.o

$(HOST_DIR)/um/subarch.o:
	$(Q)$(MAKE) $(build)=$(HOST_DIR)/um $@

$(obj)/subarch.o: $(HOST_DIR)/um/subarch.o FORCE
	$(call if_changed,copy)

targets += subarch.o

# for cleaning
subdir- += tools
