# SPDX-License-Identifier: GPL-2.0-only

obj-y += kernel/ drivers/ subarch.o

SUBARCH_DIR := arch/$(HEADER_ARCH)/um

quiet_cmd_cc_subarch.o = CC      $@
	cmd_cc_subarch.o = $(MAKE) $(build)=$(SUBARCH_DIR) subarch.o

$(SUBARCH_DIR)/subarch.o: FORCE
	$(call if_changed,cc_subarch.o)

$(obj)/subarch.o: $(SUBARCH_DIR)/subarch.o FORCE
	$(call if_changed,copy)
