name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          make ARCH=um defconfig
          make ARCH=um
          make ARCH=um mrproper
          ./tools/testing/kunit/kunit.py run
